# This file was generated by GoReleaser. DO NOT EDIT.
cask "restish" do
  name "restish"
  desc "Restish is a CLI for interacting with REST-ish HTTP APIs with some nice features built-in."
  homepage "https://rest.sh"
  version "0.21.0-hbfix.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "restish"

  on_macos do
    on_intel do
      url "https://github.com/rest-sh/restish/releases/download/v#{version}/restish-#{version}-darwin-amd64.tar.gz"
      sha256 "83af5ec9c670c87daba4164a8defa66e631ae37061b85ec1ce92c78ca0b8160e"
    end
    on_arm do
      url "https://github.com/rest-sh/restish/releases/download/v#{version}/restish-#{version}-darwin-arm64.tar.gz"
      sha256 "b3591e6813cf82518ba8f6ce7b545fb033c5258c718521ca55d315e94b6364b0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rest-sh/restish/releases/download/v#{version}/restish-#{version}-linux-amd64.tar.gz"
      sha256 "7e94197154462aac4c7f21956d6f98b746ffa1a826a5dbb092c817d96c4b6c1a"
    end
    on_arm do
      url "https://github.com/rest-sh/restish/releases/download/v#{version}/restish-#{version}-linux-arm64.tar.gz"
      sha256 "5be6aed991077ccf451f400ef2b999f85ad3b4513a0b4883b32d88d57077ff5b"
    end
  end

  # No zap stanza required
end
