# This file was generated by GoReleaser. DO NOT EDIT.
cask "restish" do
  name "restish"
  desc "Restish is a CLI for interacting with REST-ish HTTP APIs with some nice features built-in."
  homepage "https://rest.sh"
  version "0.21.0-hbfix.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "restish"

  on_macos do
    on_intel do
      url "https://github.com/rest-sh/restish/releases/download/v#{version}/restish-#{version}-darwin-amd64.tar.gz"
      sha256 "d33c6f63347bdfce45d81a5c3d5ccf41d397ad026f91d21375c40d8bfc69aa91"
    end
    on_arm do
      url "https://github.com/rest-sh/restish/releases/download/v#{version}/restish-#{version}-darwin-arm64.tar.gz"
      sha256 "2a016498ac3ced2decb69ec3cda7f428a21024b8e8f58eda6c45c7e811e0b05c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rest-sh/restish/releases/download/v#{version}/restish-#{version}-linux-amd64.tar.gz"
      sha256 "17c4bb3962d49d784b2cd5c86922dc909d40a453133f6d8defbbf1a65cd21c2f"
    end
    on_arm do
      url "https://github.com/rest-sh/restish/releases/download/v#{version}/restish-#{version}-linux-arm64.tar.gz"
      sha256 "71abd6ffe8fe424d0762f73a365cfe8ff16f82f7391b575442b8d70ca170c43a"
    end
  end

  # No zap stanza required
end
