# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RestishCsv < Formula
  desc "Restish plugin for CSV output formatting"
  homepage "https://rest.sh/"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rest-sh/restish/releases/download/v2.0.0/restish-csv-2.0.0-darwin-amd64.tar.gz"
      sha256 "8a74d65b68f0395b31d891035648ebf7212ff4af30a480f04341b5e09ad86c39"

      def install
        bin.install "restish-csv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rest-sh/restish/releases/download/v2.0.0/restish-csv-2.0.0-darwin-arm64.tar.gz"
      sha256 "931d2c778fbadfdb0b44637f3fb374766168a9077ec81c3607179f641ee13edc"

      def install
        bin.install "restish-csv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.0.0/restish-csv-2.0.0-linux-amd64.tar.gz"
      sha256 "48dfe3796d9f1ab45fbc730da6bfdc1907a4d4318eafda9dd62ac83526a80236"
      def install
        bin.install "restish-csv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.0.0/restish-csv-2.0.0-linux-arm64.tar.gz"
      sha256 "7ee704285dc1bab5133a2b3bb52aa5092b358f7b2ef4e82fd766be83370d87c6"
      def install
        bin.install "restish-csv"
      end
    end
  end

  def caveats
    <<~EOS
      Restish loads plugins from its configured plugin directory.
      To enable this plugin for Restish:

        restish plugin install #{opt_bin}/restish-csv
    EOS
  end

  test do
    system "#{bin}/restish-csv", "--rsh-plugin-manifest"
  end
end
