# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Restish < Formula
  desc "CLI for interacting with REST-ish HTTP APIs"
  homepage "https://rest.sh/"
  version "2.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rest-sh/restish/releases/download/v2.2.0/restish-2.2.0-darwin-amd64.tar.gz"
      sha256 "63c3d63629d31801f2887fa897a4d2b57b7b79686b6cbcef6084d18646705dc8"

      def install
        bin.install "restish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rest-sh/restish/releases/download/v2.2.0/restish-2.2.0-darwin-arm64.tar.gz"
      sha256 "49adbe2541032ab0d0b6bda60a1f5b7bdfeee33ed681f5245a4a561e3acf1dc5"

      def install
        bin.install "restish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.2.0/restish-2.2.0-linux-amd64.tar.gz"
      sha256 "b3f98bd9fd44d3178cfac69d71b1517f7098cf9c31d20977ea557dd220dbc238"
      def install
        bin.install "restish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.2.0/restish-2.2.0-linux-arm64.tar.gz"
      sha256 "5b230fd7d1329f0291654b1e7c728b204ea2bdc25d666952f4a4c8457c5d4f15"
      def install
        bin.install "restish"
      end
    end
  end

  test do
    system "#{bin}/restish", "--version"
  end
end
