# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RestishPkcs11 < Formula
  desc "Restish TLS signer plugin for PKCS#11 devices"
  homepage "https://rest.sh/"
  version "2.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rest-sh/restish/releases/download/v2.2.0/restish-pkcs11-2.2.0-darwin-amd64.tar.gz"
      sha256 "968663d263576f93751249ac502d1e4048dcd7f65972c4ea4ae86f5af9bde17d"

      def install
        bin.install "restish-pkcs11"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rest-sh/restish/releases/download/v2.2.0/restish-pkcs11-2.2.0-darwin-arm64.tar.gz"
      sha256 "73e5db92bdd68b94e09adbec6655af3c03506f8bbcf6fcb15c88b3132cf68f98"

      def install
        bin.install "restish-pkcs11"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.2.0/restish-pkcs11-2.2.0-linux-amd64.tar.gz"
      sha256 "b65c5cce24b595609ba7210bc7422c54e62913e35c2c5743fd0bf8964257b7cd"
      def install
        bin.install "restish-pkcs11"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.2.0/restish-pkcs11-2.2.0-linux-arm64.tar.gz"
      sha256 "8aba66774b1244976a995075ccb3e58f88cdefab314bf24b00277631ed88e583"
      def install
        bin.install "restish-pkcs11"
      end
    end
  end

  def caveats
    <<~EOS
      Restish loads plugins from its configured plugin directory.
      To enable this plugin for Restish:

        restish plugin install #{opt_bin}/restish-pkcs11

      This plugin talks to a PKCS#11 module provided by your token or smart-card
      tooling, such as OpenSC.
    EOS
  end

  test do
    system "#{bin}/restish-pkcs11", "--rsh-plugin-manifest"
  end
end
