# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RestishCsv < Formula
  desc "Restish plugin for CSV output formatting"
  homepage "https://rest.sh/"
  version "2.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-csv-2.1.1-darwin-amd64.tar.gz"
      sha256 "dc491ea317d3e66ee247ba0f490090c8ec0eb57bf2499cd69afac2abf98b164b"

      def install
        bin.install "restish-csv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-csv-2.1.1-darwin-arm64.tar.gz"
      sha256 "7909915e5ce3690191dffaaaa86657db3ac99e9f658a546674a4900ec0df6cc4"

      def install
        bin.install "restish-csv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-csv-2.1.1-linux-amd64.tar.gz"
      sha256 "39b104f56466c6e3e74b65200b54d13c7aa597ffe9049f56ff1cf9d5bcd9c939"
      def install
        bin.install "restish-csv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-csv-2.1.1-linux-arm64.tar.gz"
      sha256 "89eef42c4ceb032e2e9ab409d12fd433e0d3365c8e11f6f4bbdef72f4776ab8a"
      def install
        bin.install "restish-csv"
      end
    end
  end

  def caveats
    <<~EOS
      Restish loads plugins from its configured plugin directory.
      To enable this plugin for Restish:

        restish plugin install #{opt_bin}/restish-csv
    EOS
  end

  test do
    system "#{bin}/restish-csv", "--rsh-plugin-manifest"
  end
end
