# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RestishMcp < Formula
  desc "Restish plugin for exposing APIs as MCP tools"
  homepage "https://rest.sh/"
  version "2.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.2/restish-mcp-2.1.2-darwin-amd64.tar.gz"
      sha256 "81acc684928ec285ad78b7e3f64758e72d5e0dcbd997c683ab625fad4d458ce5"

      def install
        bin.install "restish-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.2/restish-mcp-2.1.2-darwin-arm64.tar.gz"
      sha256 "544150c2e955801676c8f9b2fe3eb0fc5de32e1853240b7434616b455fca3f21"

      def install
        bin.install "restish-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.2/restish-mcp-2.1.2-linux-amd64.tar.gz"
      sha256 "8b4d85876009b504352ec7d7807b03bf9585be34eef90a735a4e4d9b4f49b8a0"
      def install
        bin.install "restish-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.2/restish-mcp-2.1.2-linux-arm64.tar.gz"
      sha256 "0afc22cd0de537e1e162909f47c49a0f97abfb7647dd5c24135ec4e402bf0f7c"
      def install
        bin.install "restish-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      Restish loads plugins from its configured plugin directory.
      To enable this plugin for Restish:

        restish plugin install #{opt_bin}/restish-mcp
    EOS
  end

  test do
    system "#{bin}/restish-mcp", "--rsh-plugin-manifest"
  end
end
