# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RestishMcp < Formula
  desc "Restish plugin for exposing APIs as MCP tools"
  homepage "https://rest.sh/"
  version "2.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-mcp-2.1.1-darwin-amd64.tar.gz"
      sha256 "eac8a403ea93c360fddec6ad7e5a027490b9b05a72af376aaf4084f308140a5a"

      def install
        bin.install "restish-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-mcp-2.1.1-darwin-arm64.tar.gz"
      sha256 "6f2d32f7b8e2a67ce15498c8e68db4ba6ad1ac61d72108d3030b358512546e84"

      def install
        bin.install "restish-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-mcp-2.1.1-linux-amd64.tar.gz"
      sha256 "4e0041007a918f7fb554045df18d7f2dd45908c09de9cbf98ee425589014185c"
      def install
        bin.install "restish-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-mcp-2.1.1-linux-arm64.tar.gz"
      sha256 "e0b0602cc6b5f7099ddb110a4af0ff818f5693828b475c47175aae3c287b9ded"
      def install
        bin.install "restish-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      Restish loads plugins from its configured plugin directory.
      To enable this plugin for Restish:

        restish plugin install #{opt_bin}/restish-mcp
    EOS
  end

  test do
    system "#{bin}/restish-mcp", "--rsh-plugin-manifest"
  end
end
