# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RestishMcp < Formula
  desc "Restish plugin for exposing APIs as MCP tools"
  homepage "https://rest.sh/"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rest-sh/restish/releases/download/v2.0.0/restish-mcp-2.0.0-darwin-amd64.tar.gz"
      sha256 "8591a9d624aa3b380020e43bfbd8a44a55b129238c6e0efee88decfce77c75e0"

      def install
        bin.install "restish-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rest-sh/restish/releases/download/v2.0.0/restish-mcp-2.0.0-darwin-arm64.tar.gz"
      sha256 "7b86d7ea1f805eb909832f534216bd051eefa459aa0728e2952cc7cdf6910e55"

      def install
        bin.install "restish-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.0.0/restish-mcp-2.0.0-linux-amd64.tar.gz"
      sha256 "f4774d46e859a1bd084e4d8ec56b9c2b230d868669b718aed9dbe0690948d96f"
      def install
        bin.install "restish-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.0.0/restish-mcp-2.0.0-linux-arm64.tar.gz"
      sha256 "975d0bc8554314f67bc1d35726639678af56a4189a5420aac7867a2b4d8af03c"
      def install
        bin.install "restish-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      Restish loads plugins from its configured plugin directory.
      To enable this plugin for Restish:

        restish plugin install #{opt_bin}/restish-mcp
    EOS
  end

  test do
    system "#{bin}/restish-mcp", "--rsh-plugin-manifest"
  end
end
