# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RestishPkcs11 < Formula
  desc "Restish TLS signer plugin for PKCS#11 devices"
  homepage "https://rest.sh/"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rest-sh/restish/releases/download/v2.0.0/restish-pkcs11-2.0.0-darwin-amd64.tar.gz"
      sha256 "91aae989fa2f0b75636917db471064ba245ab6997d0311cb124b63e912dea0e8"

      def install
        bin.install "restish-pkcs11"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rest-sh/restish/releases/download/v2.0.0/restish-pkcs11-2.0.0-darwin-arm64.tar.gz"
      sha256 "a9c638841fa11c5db07f676c80ae4889cadd504387b028534c460a76840aa141"

      def install
        bin.install "restish-pkcs11"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.0.0/restish-pkcs11-2.0.0-linux-amd64.tar.gz"
      sha256 "0924a11e34c365bc88162248933efdfcaa4dcd9d2ef602651929c4aaf9ae29b5"
      def install
        bin.install "restish-pkcs11"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.0.0/restish-pkcs11-2.0.0-linux-arm64.tar.gz"
      sha256 "1832431bd5445b48b9d309482fb9b74982e4d2f839d64b37a1152824b3bea46a"
      def install
        bin.install "restish-pkcs11"
      end
    end
  end

  def caveats
    <<~EOS
      Restish loads plugins from its configured plugin directory.
      To enable this plugin for Restish:

        restish plugin install #{opt_bin}/restish-pkcs11

      This plugin talks to a PKCS#11 module provided by your token or smart-card
      tooling, such as OpenSC.
    EOS
  end

  test do
    system "#{bin}/restish-pkcs11", "--rsh-plugin-manifest"
  end
end
