# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Restish < Formula
  desc "CLI for interacting with REST-ish HTTP APIs"
  homepage "https://rest.sh/"
  version "2.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-2.1.1-darwin-amd64.tar.gz"
      sha256 "87ff6ec17627db37950dfd034ec6e8dd57bbf09930b6d52dd473f20cb8f805ff"

      def install
        bin.install "restish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-2.1.1-darwin-arm64.tar.gz"
      sha256 "b58bcf2a5bf52d835dd3950b404ccc085806d5021d1813ce4719d7f02ee757b7"

      def install
        bin.install "restish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-2.1.1-linux-amd64.tar.gz"
      sha256 "79763bfa31cd719b75d8419f21a40916be6cefb0718a33b87054a8a5c054346d"
      def install
        bin.install "restish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-2.1.1-linux-arm64.tar.gz"
      sha256 "31ef9526e477a86529fcb8ae81a798d6ea7b1fc8ed4cfc3e02ced6bd6ce4297b"
      def install
        bin.install "restish"
      end
    end
  end

  test do
    system "#{bin}/restish", "--version"
  end
end
