# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RestishBulk < Formula
  desc "Restish plugin for Git-like bulk resource management"
  homepage "https://rest.sh/"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.0/restish-bulk-2.1.0-darwin-amd64.tar.gz"
      sha256 "48a71c8c75e94ea32d0e39e8fcf2521b86ae31f79048b5c1936d5911edf68959"

      def install
        bin.install "restish-bulk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.0/restish-bulk-2.1.0-darwin-arm64.tar.gz"
      sha256 "514db82ab5fc3ea45cb91b5ccc0da81f6df39ae6380cc2a7e76ecaf37f16fea9"

      def install
        bin.install "restish-bulk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.0/restish-bulk-2.1.0-linux-amd64.tar.gz"
      sha256 "fdc5e1eb744d9c72d3ecb8c6caf5005930e82f7658180f4740a59edd67b91940"
      def install
        bin.install "restish-bulk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.0/restish-bulk-2.1.0-linux-arm64.tar.gz"
      sha256 "299808cf7acc13dd8a31bf39c5b5847dd9fb1614af2d397ea45e241f4038c8f7"
      def install
        bin.install "restish-bulk"
      end
    end
  end

  def caveats
    <<~EOS
      Restish loads plugins from its configured plugin directory.
      To enable this plugin for Restish:

        restish plugin install #{opt_bin}/restish-bulk
    EOS
  end

  test do
    system "#{bin}/restish-bulk", "--rsh-plugin-manifest"
  end
end
