# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RestishBulk < Formula
  desc "Restish plugin for Git-like bulk resource management"
  homepage "https://rest.sh/"
  version "2.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-bulk-2.1.1-darwin-amd64.tar.gz"
      sha256 "e798574b2f532b5c4d8147dc89d3555728f331ca4edaa8dcb8243d0a7e8a6c84"

      def install
        bin.install "restish-bulk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-bulk-2.1.1-darwin-arm64.tar.gz"
      sha256 "42306674f672bd03fa6b58b78cd0d8de5e48fab4fa1acb3eb124cfe4971842cc"

      def install
        bin.install "restish-bulk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-bulk-2.1.1-linux-amd64.tar.gz"
      sha256 "bc7872f2a780453b24eecf83ad8b01ee3f76e346d6df8030fc65aaf64434b735"
      def install
        bin.install "restish-bulk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-bulk-2.1.1-linux-arm64.tar.gz"
      sha256 "62220cab548395639d2f0245d0467ce00cbfa426879e0b09fe3cc281f4bb5c86"
      def install
        bin.install "restish-bulk"
      end
    end
  end

  def caveats
    <<~EOS
      Restish loads plugins from its configured plugin directory.
      To enable this plugin for Restish:

        restish plugin install #{opt_bin}/restish-bulk
    EOS
  end

  test do
    system "#{bin}/restish-bulk", "--rsh-plugin-manifest"
  end
end
