# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RestishPkcs11 < Formula
  desc "Restish TLS signer plugin for PKCS#11 devices"
  homepage "https://rest.sh/"
  version "2.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-pkcs11-2.1.1-darwin-amd64.tar.gz"
      sha256 "7d46b0e35941793690d76a0a09e4a83ed3fc85626108727bb89028493eed3637"

      def install
        bin.install "restish-pkcs11"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-pkcs11-2.1.1-darwin-arm64.tar.gz"
      sha256 "13133eb61c59f23254f8a9d6061cba458cc12de0daf7b82a0ecc3e3c3fd6baf9"

      def install
        bin.install "restish-pkcs11"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-pkcs11-2.1.1-linux-amd64.tar.gz"
      sha256 "fafc9ac35ff5f4c65b36f0f41cecbebfedfe1341b8c7ded0e835557c468d4fe1"
      def install
        bin.install "restish-pkcs11"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.1.1/restish-pkcs11-2.1.1-linux-arm64.tar.gz"
      sha256 "ac1306478d5f7556c4f2b7af7a5e4a827e4cbb92db90d7b60d63a25d1aeac6fe"
      def install
        bin.install "restish-pkcs11"
      end
    end
  end

  def caveats
    <<~EOS
      Restish loads plugins from its configured plugin directory.
      To enable this plugin for Restish:

        restish plugin install #{opt_bin}/restish-pkcs11

      This plugin talks to a PKCS#11 module provided by your token or smart-card
      tooling, such as OpenSC.
    EOS
  end

  test do
    system "#{bin}/restish-pkcs11", "--rsh-plugin-manifest"
  end
end
