# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RestishBulk < Formula
  desc "Restish plugin for Git-like bulk resource management"
  homepage "https://rest.sh/"
  version "2.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rest-sh/restish/releases/download/v2.2.0/restish-bulk-2.2.0-darwin-amd64.tar.gz"
      sha256 "cf79eff0cac3740f6fd4bbc5fb9b5e11b67fa92ddf3a346df91036746a9103a2"

      def install
        bin.install "restish-bulk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rest-sh/restish/releases/download/v2.2.0/restish-bulk-2.2.0-darwin-arm64.tar.gz"
      sha256 "c0c11f60d4d923c268b711ab0717720ef167926699851eb2b584c36047dfd559"

      def install
        bin.install "restish-bulk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.2.0/restish-bulk-2.2.0-linux-amd64.tar.gz"
      sha256 "f86630d676b3fc727fd5826a726ade666acf4dedb4f9061141aef5942f1c67ca"
      def install
        bin.install "restish-bulk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rest-sh/restish/releases/download/v2.2.0/restish-bulk-2.2.0-linux-arm64.tar.gz"
      sha256 "ca19c1ef66154e3ce14d001974545f448180f04567670c3f0bab92ade1d09c0c"
      def install
        bin.install "restish-bulk"
      end
    end
  end

  def caveats
    <<~EOS
      Restish loads plugins from its configured plugin directory.
      To enable this plugin for Restish:

        restish plugin install #{opt_bin}/restish-bulk
    EOS
  end

  test do
    system "#{bin}/restish-bulk", "--rsh-plugin-manifest"
  end
end
